spring:
  profiles:
    include: business
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
server:
  port: 80
mybatis-plus:
  configuration:
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启sql日志
  global-config:
    db-config:
      id-type: uuid
  mapper-locations:
  - classpath*:com/scxx/*/repository/dao/mapper/**/*.xml