spring:
  datasource:
    druid:
      username: root
      password: zl930329
      url: jdbc:mysql://47.107.155.58/kit?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false # 关闭thymeleaf的缓存,仅用于开发
logging:
#  file: logs/scxx-tool.log # 开发环境不开启文件输出
  level:
    root: info
server:
  port: 80
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启sql日志
